---
  - name: add dotdeb squeeze repo
    action: template src=templates/dotdeb.{{ ansible_lsb.codename }}.list.j2 dest=/etc/apt/sources.list.d/dotdeb.list mode=0644

  - name: download dotdeb gpg
    action: get_url url=http://www.dotdeb.org/dotdeb.gpg dest=/tmp/dotdeb.gpg mode=0400

  - name: add dotdeb gpg
    action: command apt-key add /tmp/dotdeb.gpg

  - name: apt update
    action: apt update_cache=yes
