# Common ubuntu packages
---
- hosts: webservers
  tasks:
    - name: ensure apt cache is up to date
      sudo: yes
      action: apt update_cache=yes
    - name: install dependencies 1
      sudo: yes
      action: apt pkg={{ item }}
      with_items:
        - build-essential
        - zlib1g-dev
        - libyaml-dev
        - libssl-dev
        - libgdbm-dev
        - libreadline-dev
        - libncurses5-dev
        - libffi-dev
        - curl
        - git-core
        - git
        - openssh-server
    - name: reensure apt cache is up to date
      sudo: yes
      action: apt update_cache=yes
    - name: install dependencies 2
      sudo: yes
      action: apt pkg={{ item }}
      with_items:
        - postfix
        - checkinstall
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev
        - libicu-dev
        - libbz2-dev
        - libsqlite3-dev
        # - virtualbox-guest-additions # uncomment this if virtual box guests
        - screen
        - language-pack-en-base
        - aptitude
    - name: apt upgrade
      sudo: yes
      action: apt upgrade=dist
# Remove check in .bashrc
    # - name: Remove check for interactive shell
    #   lineinfile:
    #       dest="{{ ansible_env.HOME }}/.bashrc"
    #       regexp='^\[ -z "\\$PS1" \] && return'
    #       state=absent
