 FROM 195eb90b5349
 MAINTAINER Ha Minh minhh@gmail.com

 # Update apt sources list to fetch mongodb and a few key packages
 RUN echo "deb http://archive.ubuntu.com/ubuntu precise universe" >> /etc/apt/sources.list
 RUN apt-get update

 # Expose a bunch of ports
 EXPOSE 80
